E-Commerce/mysite/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
app_name='accounts'
urlpatterns=[
url(r'^login/$',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
url(r'logout$',auth_views.LogoutView.as_view(template_name='base.html'),name='logout'),
url(r'^signup$',views.SignUp.as_view(),name='signup')
]

E-Commerce/mysite/mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path
from django.conf.urls import url,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(),name='home'),
    url(r'^$',views.HomePage2.as_view(),name='home2'),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^',include('products.urls',namespace='products')),
]
if settings.DEBUG:
 urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
 urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

E-Commerce/mysite/products/urls.py
from django.conf.urls import url
from . import views
app_name='products'
urlpatterns=[
url(r'^products/$',views.product_list,name='product_list'),
url(r'^(?P<category_slug>[-\w]+)/$',views.product_list,name='product_list_by_category'),
url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.product_detail,name='product_detail'),
]

E-Commerce/mysite/accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.
class User(auth.models.User,auth.models.PermissionsMixin):
    def __str__(self):
        return "@{}".format(self.username)

E-Commerce/mysite/products/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name=models.CharField(max_length=200,db_index=True)
    slug=models.SlugField(max_length=200,db_index=True,unique=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:product_list_by_category',args=[self.slug])

class Product(models.Model):
     category=models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
     name=models.CharField(max_length=200,db_index=True)
     slug=models.SlugField(max_length=200,db_index=True)
     image=models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
     description=models.TextField(blank=True)
     price=models.DecimalField(max_digits=10,decimal_places=2)
     stock=models.PositiveIntegerField()
     available=models.BooleanField(default=True)
     created=models.DateTimeField(auto_now_add=True)
     updated=models.DateTimeField(auto_now=True)

     class Meta:
         ordering=('-created',)
         index_together=(('id','slug'),)

     def __str__(self):
         return self.name

     def get_absolute_url(self):
         return reverse('products:product_detail',args=[self.id,self.slug])

E-Commerce/mysite/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    class Meta:
        fields=('username','email','password1','password2')
        model=get_user_model()
        def __init__(self,*args,**kwargs):
            super().__init__(*args,**kwargs)
            self.fields["username"].label="Display name"
            self.fields["email"].label="Email address"

E-Commerce/mysite/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from .import forms
from django.views.generic import CreateView

# Create your views here.
class SignUp(CreateView):
    form_class=forms.UserCreateForm
    success_url=reverse_lazy("login")
    template_name="accounts/signup.html"

E-Commerce/mysite/mysite/views.py
from django.views.generic import TemplateView
class HomePage(TemplateView):
    template_name='base.html'

class HomePage2(TemplateView):
    template_name='base2.html'

E-Commerce/mysite/products/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,Product

# Create your views here.
def product_list(request,category_slug=None):
        category=None
        categories=Category.objects.all()
        products=Product.objects.filter(available=True)
        if category_slug:
          category=get_object_or_404(Category,slug=category_slug)
          products=products.filter(category=category)
        return render(request,'products/list.html',{'category':category,
                                                 'categories':categories,
                                                 'products':products })
def product_detail(request,id,slug):
    product=get_object_or_404(Product,id=id,slug=slug,available=True)
    return render(request,
               'products/detail.html',
               {'product':product})

E-Commerce/mysite/accounts/templates/accounts/login.html
{%extends "base.html"%}
{%load bootstrap4%}
{%block content%}
<div class="container">
  <h1>Log In</h1>
  <form method="POST">
    {%csrf_token%}
    {%bootstrap_form form%}

    <input type="submit" class="btn btn-default" value='Login' id='login'>

  </form>

</div>
{%endblock%}

E-Commerce/mysite/accounts/templates/accounts/signup.html
{%extends "base.html"%}
{% load bootstrap4 %}

{%block content%}
<div class="container">
  <h1>Sign Up</h1>
  <form  method="POST">
    {%csrf_token%}
    {%bootstrap_form form%}
    <input type="submit"class="btn btn-default" id="submit">


  </form>

</div>
<body>

</body>
{% endblock %}

E-Commerce/mysite/products/templates/products/detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
{%include "navbar.html"%}
<div class="row">
  <div style="margin-top:70px">
  <img src="{% if product.image %}{{product.image.url}} {% endif %}" alt="Mobile image" style="width:500px">
  </div>
<div class="product-description">
        <b><p id="product-name">{{product.name}}</p></b>
          <p> <b>Price: Rs {{product.price}} Only!</b> </p>
          <p> <b>Specifications : {{product.description|safe|linebreaksbr}}</b></p>
          <p><b>Stock: Hurry up! only {{product.stock}} left</b></p>
          <button type="button" class="add-to-cart">Add to Cart</button>
          <button type="button" class="add-to-cart">Buy Now</button>

</div>

</div>

{% endblock %}

E-Commerce/mysite/products/templates/products/list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
{%include "navbar.html"%}
<div class="main-wrap">
<div class="sidebar"><h3>Categories</h3>
  {% for c in categories %}
  <ol style="margin-left:20px">
  <li {% if category.slug == c.slug %}  {% endif %} style="list-style:none">
                    <a href="{{ c.get_absolute_url }}" class="btn btn-primary">{{ c.name }}</a>
  </li>

  </ol>

  {% endfor %}

</div>

</div>
{% for product in products %}
<div class="column">
  <a href="{{ product.get_absolute_url }}">
<img src="{% if product.image %}{{product.image.url}}{% endif %}" alt="Mobile image" style="height:300px; width:300px" id="product-image">
  </a>
  <p style="font-size:18px">

<a href="{{product.get_absolute_url}}" style="margin-left:190px">{{product.name}}</a>
<br>
<a href="{{product.get_absolute_url}}"style="margin-left:150px">Now at Rs {{product.price}}</a>
  </p>
  <button type="button" class="add-to-cart">Add to Cart</button>


</div>

{%endfor%}

{%endblock%}

E-Commerce/mysite/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">

  <head>
<meta charset="utf-8">
<title>Online Shop</title>
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
{%block content%}
{%if user.is_authenticated%}
{% include "navbar.html" %}
{%else%}
{%include "navbar2.html" %}
{%endif%}
  </head>

  <body>
    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="{%static 'images/First-slide.jpg'%}" id='first-image'>
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{%static 'images/Second-slide.jpg'%}" alt="Second slide" id="second-image">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="{%static 'images/Third-slide.jpg'%}" alt="Third slide" id="third-image">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div class="centered"><i>
Get 50% discount on the latest products including smartphones,watches and many more!
</i>

</div>

</div>
<h4><i>Smartphones</i></h4>

<div class="row">

  <div class="column">
    <img src="{%static "images/smart1.jpg"%}" alt="Smartphone" style="width:100%">
    <h5><i>Rs10,000</i></h5>
  </div>
  <div class="column">
    <img src="{%static "images/smart2.jpg"%}" alt="Smartphone" style="width:100%">
    <h5><i>Rs8,000</i></h5>
  </div>
  <div class="column">
    <img src="{%static "images/smart3.jpg" %}" alt="Smartphone" style="width:100%">
    <h5><i>Rs15,000</i></h5>
  </div>
</div>


<h4><i>Watches</i></h4>
<div class="row">

  <div class="column">
    <img src="{%static "images/watch1.jpg"%}" alt="Watch" style="width:100%">
    <h5><i>Rs5,000</i></h5>
  </div>
  <div class="column">
    <img src="{%static "images/watch2.jpg"%}" alt="Watch" style="width:100%">
    <h5><i>Rs1000</i></h5>
  </div>
  <div class="column">
    <img src="{%static "images/watch3.jpg" %}" alt="Watch" style="width:100%">
    <h5><i>Rs2,000</i></h5>
  </div>
</div>
<h4><i>Laptops</i></h4>
<div class="row">

  <div class="column">
    <img src="{%static "images/lap1.jpg"%}" alt="Laptop" style="width:100%">
    <h5><i>Rs50,000</i></h5>
  </div>
  <div class="column">
    <img src="{%static "images/lap2.jpg"%}" alt="Laptop" style="width:100%">
    <h5><i>Rs2,00000</i></h5>
  </div>
  <div class="column">
    <img src="{%static "images/lap3.jpg" %}" alt="Laptop3" style="width:100%">
    <h5><i>Rs75,000</i></h5>
  </div>
</div>
<h4> <i>Refrigerators</i></h4>
<div class="row">

  <div class="column">
    <img src="{%static "images/ref1.jpg"%}" alt="Smartphone" style="width:100%">
    <h5><i>Rs45,000</i></h5>
  </div>
  <div class="column">
    <img src="{%static "images/ref2.jpg"%}" alt="Smartphone" style="width:100%">
    <h5><i>Rs50,000</i></h5>
  </div>
  <div class="column">
    <img src="{%static "images/ref3.jpg" %}" alt="Smartphone" style="width:100%">
    <h5><i>Rs38,000</i></h5>
  </div>
</div>
<h4> <i>Washing Machines</i></h4>
<div class="row">

  <div class="column">
    <img src="{%static "images/wash1.jpg"%}" alt="Smartphone" style="width:100%">
    <h5><i>Rs38,000</i></h5>
  </div>
  <div class="column">
    <img src="{%static "images/wash2.jpg"%}" alt="Smartphone" style="width:100%">
    <h5><i>Rs80,000</i></h5>
  </div>
  <div class="column">
    <img src="{%static "images/wash3.jpg" %}" alt="Smartphone" style="width:100%">
    <h5><i>Rs20,000</i></h5>
  </div>
</div>

  </body>


  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="{%static "js/.js" %}">

</script>
{%include "footer.html"%}

</html>

{%endblock%}

E-Commerce/mysite/templates/footer.html
<footer>
<h6>&copy rights reserved
</h6>
</footer>

E-Commerce/mysite/templates/navbar.html
<nav class="navbar fixed-top navbar navbar-expand-lg navbar-dark bg-dark">

  <a class="navbar-brand" href="#"> <i id="heading"></i>Shopping Cart</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#" id="home">Home <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link active " href="#"id="about">About</a>
      </li>

            <li class="nav-item">
              <a class="nav-link active " href="{% url 'products:product_list' %}"id="products">Products</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active " href="{%url 'accounts:logout'%}"id="logout">Logout</a>
            </li>

              <p id="user"><i>Welcome @{{request.user.username}}</i></p>

    </ul>

  </div>

  <h6> <i>Cart</i> </h6>

  <a href="#" id="cart"><i class="ion-android-cart"></i></a>


</nav>

E-Commerce/mysite/templates/navbar2.html
<nav class="navbar fixed-top navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#"> <i id="heading"></i>Shopping Cart</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">

    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#" id="home">Home <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link active " href="#"id="about">About</a>
      </li>


      <li class="nav-item">
        <a class="nav-link active " href="{% url 'accounts:signup' %}"id="signup">Signup</a>
      </li>
       <li class="nav-item">
         <a class="nav-link active " href="{% url 'accounts:login' %}"id="Login">Login</a>
       </li>


    </ul>

  </div>
  <h6> <i>Cart</i> </h6>
  <a href="#" id="cart"><i class="ion-android-cart"></i></a>

</nav>